### ISSUE TITLE
Configuration inside pyproject.toml

### ISSUE THREAD

**Issue by dryobates** [kidosoft/Morelia#119]
With increasing adoption of [PEP 518](https://www.python.org/dev/peps/pep-0518/) and not so useful current morelia's configuration we could transition into new format.

Similary to [black](https://black.readthedocs.io/en/stable/pyproject_toml.html) morelia would use pyproject.toml file from current directory, and if not found would search higher in the file system until it would find .git or .hg directory. If neither was found it would try ~/.config/morelia/morelia.toml as last resort.

Morelia's main key would be "tool.morelia" with subkeys marking sections that can be provided to "verify" function (#118 ).

Directly in section would be keys:
wip - boolean marking if it's work-in-progress run (which would allow verifing feature even when not all steps where defined)
matchers - array with matcher names tried in given order

Next subkey would be "output". It will be list of output configurations.

Below example configuration:

```toml
[tool.morelia.default] 
wip=false 
matchers=["parse", "regex", "method"] 

[[tool.morelia.default.output]]
format="terminal"
color=false
[[tool.morelia.default.output]]
# different outputs have different parameters
format="html"
file="output/{feature}.html"
[[tool.morelia.default.output]]
format="json"
dest="file://output/{feature}.json"
[[tool.morelia.default.output]]
format="json"
dest="http://example.com"

[tool.morelia.custom1] 
wip=true 
matchers=["parse"] 
[[tool.morelia.custom1.output]]
format="terminal"
color=true
```
